
language: node_js

node_js:
    - 8
    - 10
    - 12

cache:
    directories:
      - node_modules

scripts:
    - yarn test

services:
    - redis-server
    - mongodb

after_success:  yarn coverage
